/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#faf9f7",
        "surface-dim": "#dbdad8",
        "surface-bright": "#faf9f7",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f1",
        "surface-container": "#efeeec",
        "surface-container-high": "#e9e8e6",
        "surface-container-highest": "#e3e2e0",
        "on-surface": "#1a1c1b",
        "on-surface-variant": "#444748",
        "inverse-surface": "#2f3130",
        "inverse-on-surface": "#f1f1ef",
        outline: "#747878",
        "outline-variant": "#c4c7c7",
        "surface-tint": "#5f5e5e",
        primary: "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1c1b1b",
        "on-primary-container": "#858383",
        "inverse-primary": "#c8c6c5",
        secondary: "#5e5e5e",
        "on-secondary": "#ffffff",
        "secondary-container": "#e0dfdf",
        "on-secondary-container": "#626362",
        tertiary: "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#161f00",
        "on-tertiary-container": "#7b8a4d",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#e5e2e1",
        "primary-fixed-dim": "#c8c6c5",
        "on-primary-fixed": "#1c1b1b",
        "on-primary-fixed-variant": "#474746",
        "secondary-fixed": "#e3e2e1",
        "secondary-fixed-dim": "#c7c6c5",
        "on-secondary-fixed": "#1a1c1c",
        "on-secondary-fixed-variant": "#464746",
        "tertiary-fixed": "#d9eaa3",
        "tertiary-fixed-dim": "#bdce89",
        "on-tertiary-fixed": "#161f00",
        "on-tertiary-fixed-variant": "#3e4c16",
        background: "#faf9f7",
        "on-background": "#1a1c1b",
        "surface-variant": "#e3e2e0",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        "container-padding": "20px",
        "container-padding-lg": "24px",
        gutter: "16px",
        "section-gap": "80px",
        "section-gap-lg": "120px",
      },
      maxWidth: {
        content: "1280px",
      },
      fontFamily: {
        display: ["'Playfair Display'", "serif"],
        body: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-md": ["28px", { lineHeight: "1.3", fontWeight: "500" }],
        "headline-sm": ["22px", { lineHeight: "1.3", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      boxShadow: {
        ambient: "0 0 30px rgba(0,0,0,0.04)",
        "nav-top": "0 -4px 30px rgba(0,0,0,0.04)",
      },
      backdropBlur: {
        xs: "2px",
      },
    },
  },
  plugins: [],
};
